---
description: Local server configuration for development and testing.  PLEASE DON'T use this configuration for PRODUCTION.
environment:
  - name: APP_HOME
    description: Inner Circle base directory. (When launched from starter script this should be set automatically.)
  - name: POSTGRES_HOSTNAME
    description: Postgres hostname.
    default: localhost
  - name: POSTGRES_PORT
    description: Postgres port.
    default: 5432
  - name: POSTGRES_DB
    description: Postgres database.
    default: innercircle
  - name: POSTGRES_USER
    description: Postgres username.
    default: innercircle
  - name: POSTGRES_PASSWORD
    description: Postgres password.
arguments:
  - short: b
    long: baseUrl
    description: Base URL for the application.  All redirects are resolved relative to this.
    default: http://localhost:8080
  - short: s
    long: staticAssetDir
    description: Directory to serve static assets from.
    default: server/build/static-assets
  - short: f
    long: localFilesDir
    description: Directory to serve files (images and videos) from.
    default: server/src/main/config/dev/content/assets
---
modules:
  - class: com.github.brosander.innercircle.config.LocalAssetResolverModule
    baseDir: ${env.APP_HOME}
  - class: com.github.brosander.innercircle.entrypoints.InnerCircleDataloadModule
    jsonFile: server/src/main/config/dev/content/content.json
  - class: com.github.brosander.innercircle.services.ServiceContextModule
    baseUrl: ${args.baseUrl}
  - class: com.github.brosander.innercircle.entrypoints.InnerCircleServerModule
    traceRouting: true
  - class: com.github.brosander.innercircle.services.ApiV1Module
  - class: com.github.brosander.innercircle.services.ClientModule
    staticFolder: ${args.staticAssetDir}
  - class: com.github.brosander.innercircle.services.files.LocalFilesModule
    baseDir: ${args.localFilesDir}
  - class: com.github.brosander.innercircle.services.security.session.CookieSessionModule
    sessionHashKey: ${func.randomHex(64)}
  - class: com.github.brosander.innercircle.model.connection.PostgresConnectionFactoryModule
    hostname: ${env.POSTGRES_HOSTNAME}
    port: ${env.POSTGRES_PORT}
    db: ${env.POSTGRES_DB}
    user: ${env.POSTGRES_USER}
    password: ${env.POSTGRES_PASSWORD}
  - class: com.github.brosander.innercircle.services.security.authentication.DevOnlyTrustingAuthenticationProviderModule