---
description: Dataload into Postgres.
environment:
  - name: POSTGRES_HOSTNAME
    description: Postgres hostname.
    default: localhost
  - name: POSTGRES_PORT
    description: Postgres port.
    default: 5432
  - name: POSTGRES_DB
    description: Postgres database.
    default: innercircle
  - name: POSTGRES_USER
    description: Postgres username.
    default: innercircle
  - name: POSTGRES_PASSWORD
    description: Postgres password.
arguments:
  - short: f
    long: dataloadFile
    description: Json file containing data to load.
  - short: n
    long: scraperName
    description: Name of user that did the scrape.  They will be added to all circles as they couldn't have scraped if it wasn't shared with them.
    required: false
---
modules:
  - class: com.github.brosander.innercircle.model.connection.PostgresConnectionFactoryModule
    hostname: ${env.POSTGRES_HOSTNAME}
    port: ${env.POSTGRES_PORT}
    db: ${env.POSTGRES_DB}
    user: ${env.POSTGRES_USER}
    password: ${env.POSTGRES_PASSWORD}
  - class: com.github.brosander.innercircle.entrypoints.InnerCircleDataloadModule
    jsonFile: ${args.dataloadFile}
    scraperName: ${args.scraperName}
